### ISSUE TITLE
Selecting Folder does not seem to filter list

### ISSUE THREAD

**Issue by adolgov** [tsquillario/Jamstash#151]
I'm assuming that selecting a specific folder (as opposed to "All Folders") should filter the content list below; however, it always just shows the entire server content, even after a manual page refresh. This tends to be problematic when users have mixed media (i.e. music and video), but only want to access one type in a session.

**Comment by mad1993max** [comment]
i am still experiencing this error on the beta as on the stable jamstash

**Comment by tsquillario** [comment]
I'll take a look at this again.
