### ISSUE TITLE
Jamstash Beta - Media Keys in Chrome - osx

### ISSUE THREAD

**Issue by dmarkley-shop** [tsquillario/Jamstash#189]
Media keys using keysocket is not working on the Jamstash beta site. The media keys work properly on the main site. 

OS X 10.9.5
Chrome 39.0.2171.95
Keys Socket Media Keys 0.6.0
Noticed issue a few days ago.

Not actually a big deal, just wanted to make sure you knew. Thanks for a great product!

**Comment by abeudin** [comment]
i have the same probleme

**Comment by tsquillario** [comment]
Any input on this? @borismus

**Comment by borismus** [comment]
Jamstash support was contributed by someone else, sorry I haven't tested this particular service.
