### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by michaeldeeter** [tsquillario/Jamstash#191]
Viewing the Library... select a folder in the list at the left.

The dropdown that says "Default Sort" does nothing.  Changing the dropdown has no effect.

Tried in Chrome and Firefox.

**Comment by tsquillario** [comment]
Fixed on http://beta.jamstash.com

**Comment by michaeldeeter** [comment]
Currious if there was any way to toggle the sort as well?

**Comment by tsquillario** [comment]
What do you mean by toggle?

**Comment by michaeldeeter** [comment]
Changing the sort direction from accending to descending.
