### ISSUE TITLE
Unable to connect to subsonic server

### ISSUE THREAD

**Issue by matsboisen** [tsquillario/Jamstash#192]
I have been using a local copy of Jamstash 3.3 for a long time and it has worked fine. But when I now try and upgrade to the newest version 4.3 I get an error as soon as I save my setting "Unable to connect to Subsonic Server". I can connect to the demo server. My server uses a different port - 4040 -   but the demo server has no port specified. Maybe that can be an issue.

I have also tried the Chrome App. I uninstalled it and installe it again. I get the same error in the Chrome app.

I have tried to enable "debug mode" but I cannot see any debug info.

I am running Chrome on Windows 8.1

**Comment by tsquillario** [comment]
- Try changing Settings > Protocol
- Hit F12 and look at the Console and Network tab
- Are you using http/https?

**Comment by matsboisen** [comment]
I have tested it.Here is my error log:

**Comment by matsboisen** [comment]
Ok, I need to use jsonp. It seems to connect to the server but I still see no artists and songs. I get another error when doing so.

scripts.min.4c7ea77d.js:1 Logged In: true
scripts.min.4c7ea77d.js:1 Current Path: /settings
vendor.min.65dc2836.js:5 TypeError: Cannot read property 'status' of undefined
    at http://jamstash.com/scripts/scripts.min.4c7ea77d.js:2:17223
    at k (http://jamstash.com/scripts/vendor.min.65dc2836.js:5:7014)
    at http://jamstash.com/scripts/vendor.min.65dc2836.js:5:7675
    at k.$eval (http://jamstash.com/scripts/vendor.min.65dc2836.js:5:12931)
    at k.$digest (http://jamstash.com/scripts/vendor.min.65dc2836.js:5:11456)
    at k.$apply (http://jamstash.com/scripts/vendor.min.65dc2836.js:5:13250)
    at i (http://jamstash.com/scripts/vendor.min.65dc2836.js:4:24010)
    at r (http://jamstash.com/scripts/vendor.min.65dc2836.js:4:26418)
    at XMLHttpRequest.w.onreadystatechange (http://jamstash.com/scripts/vendor.min.65dc2836.js:4:26994)

**Comment by Hyzual** [comment]
I've noticed an error in the settings when hitting "save", I think it's related to that.
in `main-controller.js`, line 69 :

```javascript
$scope.ping().then(function(data) {
    if (data["subsonic-response"].status == 'ok') {
```

I think the server responded XML instead of json, causing the error. Haven't digged further but hopefully it's a start

**Comment by tsquillario** [comment]
Pushed a few changes to http://beta.jamstash.com that should fix the errors.

**Comment by frankeleone** [comment]
thanks! fixed it for me.
Frank

**Comment by matsboisen** [comment]
When I try beta.jamstash.com I get "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://beta.jamstash.com' is therefore not allowed access." when I use both json and jsonp. Should I set som setting somewhere?
