### ISSUE TITLE
Getting Started guide out of date

### ISSUE THREAD

**Issue by shrimpza** [tsquillario/Jamstash#197]
Hi,

I did a self-hosted installation of Jamstash, and found the getting started guide (manual installation) rather out of date. I tried deploying the "dist" directory to my web server, which didn't work, since there are no JS files present there; tried deploying the "app" directory, but all the external dependencies are missing from there too (I'm not at all familiar with the dev environment used for this project, so the presence of a non-deployable "dist" directory was quite confusing).

Eventually, I performed the following steps:

1. Install `node`
2. Install `npm`
3. Install `bower`
4. `$ npm install`
5. `$ bower install`
6. Copy the generated `bower_components` directory to `app/bower_components`
7. Deploy contents of `app` to my web server

Everything works this way, and I'm happy with the end result, but I think some clarification to the manual installation instructions may help others in the future.

Otherwise thanks for the great tool :+1:

**Comment by Hyzual** [comment]
Weird... the dist directory should contain everything, the JS files are in `dist/scripts`

**Comment by shrimpza** [comment]
Hi

You are quite right, I've redeployed from the `dist` directory, and it worked first time. I was seriously pulling my hair out yesterday, trying to figure out the above steps.

Apologies for my lapse in sanity, I'll now go hide in shame...

**Comment by Hyzual** [comment]
Haha don't die out of shame just yet :) We all get confused.
I think you still pointed to a real problem : getting started when you want
to dev / contribute. We can certainly make it clearer. I'll look into it
and start from the list you provided. Thanks for that !
Le Mon Jan 26 2015 at 18:55:30, Kenneth Watson <notifications@github.com> a
écrit :
