### ISSUE TITLE
Using - and = buttons on keyboard stops playback

### ISSUE THREAD

**Issue by secondsabre** [tsquillario/Jamstash#199]
Don't know when this started happening (last week or so), but when I try and use the standard Vol Up/Down buttons (-/_  and  =/+) on my keyboard, the song stops playing and Jamstash seems to freeze.  The song title in the Now Playing bar just turns into a single forward slash (/), and I have to refresh the page/app in order to continue playing anything.

Would be really nice to have a volume slider back, too, but fixes are more important than features.  Thanks, all!

**Comment by Hyzual** [comment]
Noted, I'll try and fix this ASAP (which probably means this weekend).

Le Tue Feb 03 2015 at 17:00:17, secondsabre <notifications@github.com> a
écrit :

**Comment by tsquillario** [comment]
Fixes deployed to http://beta.jamstash.com
