### ISSUE TITLE
Last.fm Scrobbling

### ISSUE THREAD

**Issue by hndrewaall** [tsquillario/Jamstash#200]
On the Subsonic page this is supposed to be a feature, but apparently it isn't? I would like it. Thanks!

**Comment by johngouf** [comment]
Why is this closed? It doesn't seem to be supported.

**Comment by ticklemynausea** [comment]
Subsonic does support it. Since jamstash is just a frontend for subsonic, this does not concern Jamstash.

Maybe add an interface to allow configuration and reduce confusion?
