### ISSUE TITLE
Jamstash not loading, showing Directory/Jamstash

### ISSUE THREAD

**Issue by djesys** [tsquillario/Jamstash#205]
Hi there !
Installed as instructed, but nginx is not serving the page. Instead it shows me the content of the Jamstash directory. 

My nginx- vhost config: 

server {
        listen  80;
        server_name sub.DOMAIN.com;

        location / {
                proxy_pass      http://127.0.0.1:4040;
                proxy_redirect  off;
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }
   }

**Comment by Hyzual** [comment]
Hi !

I'm not yet super-familiar with nginx configuration but it seems that you're trying to do a reverse-proxy to Subsonic. I can't really help you with that.
Jamstash really is only made of static html, css, javascript and images so you should be able to serve those directly (without proxy_pass). Just download the `dist/` folder.
If you're familiar with [Docker](https://www.docker.com/), I've created an image with Jamstash v4.4.2 installed on nginx. See it on [Docker Hub](https://registry.hub.docker.com/u/hyzual/jamstash/).
Hope it helps !
