### ISSUE TITLE
Using -/_ to lower audio level hangs the Jamstash HTML5 player.

### ISSUE THREAD

**Issue by bshermis** [tsquillario/Jamstash#209]
When using the -/_ key to lower the audio (as directed on the settings page) on a Chrome window, the audio stops and seemingly can not be restarted. Only killing the page and starting over will regain audio playback.

Early-2011 MacBook Pro with OS X v10.10.2, Chrome Browser v40.0.2214.115 (64-bit).

**Comment by dmarkley-shop** [comment]
I can confirm this issue using:
Chrome  41.0.2272.118 (64-bit)
OS X 10.10.2

**Comment by Hyzual** [comment]
Hi, sorry for the late reply.
This should be fixed on http://jamstash.com in the latest version (4.4.5). As I don't own a Mac, I've tested this on Windows and Linux Chrome.
Let me know how it is on your side so we can close the issue.

**Comment by dmarkley-shop** [comment]
Looks to be resolved for me. Thank you!

**Comment by tsquillario** [comment]
@Hyzual making good use of the Webhooks :)

**Comment by Hyzual** [comment]
Yes, they're very useful :D. I hope you didn't mind me pushing to master, I
thought that version had been a long time in beta and could safely be
published.

Le ven. 29 mai 2015 à 15:07, tsquillario <notifications@github.com> a
écrit :
