### ISSUE TITLE
Fetch missing album art from Last.fm/Amazon

### ISSUE THREAD

**Issue by ronilaukkarinen** [tsquillario/Jamstash#210]
I like the way [MusicCabinet](https://github.com/hakko/musiccabinet) deals with missing album art (gets them from Last.fm). Any way to get this kind of functionality instead of idtags? I have quite massive library and going through all the albums is a very time consuming task.

**Comment by tsquillario** [comment]
I guess MusicCabinet doesn't actually update the mp3 files with the cover art. While I think this is useful, I think it is better implemented in Subsonic or MusicCabinet as I'm just using the API.
