### ISSUE TITLE
Can't install beta app because of common/background.js

### ISSUE THREAD

**Issue by ssfrr** [tsquillario/Jamstash#215]
When I try to install the beta app from the chrome web store I get the error:

```
An error has occurred
Package is invalid. Details: 'Could not load background script 'common/background.js'.'.
```

Chromium Version 41.0.2272.76 Ubuntu 14.04 (64-bit)

**Comment by tsquillario** [comment]
I seem to be getting this too, I'll take a look!

**Comment by tsquillario** [comment]
Fixed!
