### ISSUE TITLE
Beta still doesn't seem to save settings

### ISSUE THREAD

**Issue by ssfrr** [tsquillario/Jamstash#216]
I thought the beta version should save my login settings across app closures, but so far that doesn't seem to be working. I'm running Chromium on Linux, and I have the app installed from the Chrome app thingy.

I put in my login information then click the headphones to go into my library. Then if I close the tab and re-open it my login info is gone. Is there something else I'm supposed to do to enable saving my login?

**Comment by Hyzual** [comment]
Hi !
It should save all your settings correctly, I just re-tested it.

![Save settings](http://i.imgur.com/PbTRLyX.png)

Did you click on the "Save" button in the settings ? You might have to scroll a little to see it.
When you click it, it should redirect you to the library (same as clicking the headphones icon) and a small message "Settings Updated!" should appear at the bottom-right corner of the screen.

**Comment by ssfrr** [comment]
Whoops! I totally missed the save button. Thanks.

**Comment by Hyzual** [comment]
I'm glad I could help you :-)

Le Mer 17 Juin 2015 17:02, Spencer Russell <notifications@github.com> a
écrit :
