### ISSUE TITLE
Unreadable album title when using dark theme

### ISSUE THREAD

**Issue by UrbanCMC** [tsquillario/Jamstash#217]
I'm not sure why nobody mentioned it before, but when using the dark theme it is absolutely impossible to read the name of an album, as you can see in the attached image.

![jamstash_dark_barelyvisiblealbumname](https://cloud.githubusercontent.com/assets/9725089/8437473/6bce507e-1f5f-11e5-83a6-9c5fd99f28ee.JPG)

**Comment by Hyzual** [comment]
I could reproduce it on Firefox, was it the browser you were using ?
It'll be fixed for the next beta version.

**Comment by Hyzual** [comment]
The newest beta version 4.6.0 is available on http://beta.jamstash.com.
This issue should be fixed. Thanks for reporting it ! Please reopen it if there is still a problem.
