### ISSUE TITLE
Support for Madsonic REST API 2.0.0

### ISSUE THREAD

**Issue by troycarpenter** [tsquillario/Jamstash#219]
Please add support, at least in the Beta version, for Madsonic REST API 2.0.0 used in the new 6.0 beta releases.

See:  http://beta.madsonic.org/pages/api.jsp

**Comment by apastuszak** [comment]
What does this get you over the standard Subsonic API?

**Comment by apastuszak** [comment]
I'd prefer adding the Ampache's XML based APIs, but that's for another bug.

**Comment by troycarpenter** [comment]
:) If you want to give it a go, I'm willing to test to make sure it can access the new server base.

**Comment by troycarpenter** [comment]
It looks like Mad implemented a backwards compatible API mode in his last beta.  Jamstash is working again.

**Comment by ghenry22** [comment]
yep madsonic has a backward compatible API now. 

So any subsonic client will work with it again.  This could be closed.

**Comment by Helios747** [comment]
Sort of.

The backwards compatible API is now restricted to premium licenses. Free users can only use players that have specifically implemented the Madsonic API.

Does this make the issue valid again or does nobody care enough to support this? :P
