### ISSUE TITLE
Select all queue items

### ISSUE THREAD

**Issue by miicha** [tsquillario/Jamstash#220]
The intention to ask for a "select all queue items" is that I usually put songs/albums I'd like to hear in the queue. That way I build a playlist which I'd like to be able to save for later. Up to now I couldn't find a way to save that queue to a permanent playlist except to klick at every single song.

If I have some time I will try to dive into the code and implement such a button, but I think it will be much easier for someone familiar with the structure. I would be really happy about such a feature or at least a starting point where and how such a feature should be implemented

**Comment by Hyzual** [comment]
Hi,

I think it's a great idea ! At one point I also wrote down an idea to create a playlist from the playing queue but I never got around implementing it.

I would very much appreciate your help ! Lately I've been quite busy and haven't taken much time to work on Jamstash.
I can point you to the files that need to be modified to implement this :

- [ ] `/app/queue/queue.html` : add an `<a>` containing an icon to toggle selection
- [ ] `/app/images/`: add the icon's image (`.png`or `.svg`)
- [ ] `/app/queue/queue.js` : add a function to toggle all the queue's songs' `selected` property. The queue is `player.queue` which is an array of `song` objects, which all have a `selected` propery.
- [ ] `/app/queue/queue_test.js` : add unit tests that verify that songs that weren't selected become selected and that songs that were selected become unselected. If you aren't comfortable writing unit tests I could do it for you.

Here is our [wiki page on how to contribute](https://github.com/tsquillario/Jamstash/wiki/Contributing) for help with the tools used to work on Jamstash.

**Comment by Hyzual** [comment]
This should be implemented in v4.6.3 available on http://beta.jamstash.com

Let me know if this was what you had in mind with the toggle functionality and I'll close the issue.

**Comment by tsquillario** [comment]
Running the latest version, seems to be working good :)

**Comment by miicha** [comment]
Yeah that looks good.
First tests look very good so it can be closed here
