### ISSUE TITLE
Cannot install Jamstash... need help ;)

### ISSUE THREAD

**Issue by pcace** [tsquillario/Jamstash#232]
Hi, 
I have followed the Jamstash-install instructions for a Linux system, but i am not able to run it! Whats the matter there? i get this: --> any idea?

![bildschirmfoto 2016-02-14 um 14 12 31](https://cloud.githubusercontent.com/assets/1011875/13033851/66e4a048-d325-11e5-9625-c2769c418de2.png)
![bildschirmfoto 2016-02-14 um 14 13 47](https://cloud.githubusercontent.com/assets/1011875/13033852/66ecd7b8-d325-11e5-9679-aaf7dd537b91.png)

**Comment by Hyzual** [comment]
What happens if you browse to http://server:8080/subsonic/Jamstash/dist/ ?
The `dist/` forlder contains all the javascript / css / html / images in minified format and should contain an index.html file for your browser to display.

**Comment by pcace** [comment]
wow, that was fast! It helps, and works now. 
Is this something to worry about or something i just have to accept ;)?

**Comment by Hyzual** [comment]
Glad to read that :). Nothing to worry about.
It seems we forgot to mention that part in the Getting started doc, I'll update it right away.
Anyway, if you want to browse to `Jamstash/` just empty the folder at `/var/subsonic/jetty/[number]/webapp/Jamstash` and only move the contents of the `dist/` folder to it.
