### ISSUE TITLE
settings to connect to localhost

### ISSUE THREAD

**Issue by arielelkin** [tsquillario/Jamstash#233]
What settings should I put into Jamstash if I want to connect to `localhost`? 

![image](https://cloud.githubusercontent.com/assets/1756909/14137364/cc5b8ff8-f667-11e5-8580-32e27a008b03.png)

Or do I have to put the server's IP?

**Comment by Hyzual** [comment]
Putting `http://localhost` for the server should work, I just tried it using containers for jamstash and subsonic. It goes without saying that you should also change it to `http://localhost:4040` if you're using port 4040.

Does it work for you ?

**Comment by arielelkin** [comment]
No. 

As a matter of fact, I've setup an Ampache (Ampache is exposing a Subsonic API) instance running in a Docker container, and copied Jamstash's files to the container's `/var/www/` directory. Jamstash displays fine, but if I specify `http://localhost` as the server I get an `Error when contacting the Subsonic server. The requested data was not found.` (see https://github.com/tsquillario/Jamstash/issues/234)

**Comment by Hyzual** [comment]
From a quick glance at Ampache's github repo, it seems that its Subsonic API only supports XML. Can you confirm that this is the case ? I didn't know about Ampache before you mentioned it.

Jamstash can only deal with a JSON API (or JSONP), so if Ampache only provides XML then they are incompatible.

**Comment by arielelkin** [comment]
indeed, Ampache [only provides XML](https://github.com/ampache/ampache/wiki/XML-API)... 

As a workaround, you can install a Subsonic instance and tell it to grab its data from Ampache. Ampache can provide a Subsonic-compatible API, and Subsonic can subsequently serve a JSON API. Jamstash would then have to connect to Subsonic's port. We can get it to work that way. 

But it's a bit of a workaround. Generally, it'd be great if Jamstash could also work with Ampache!

**Comment by arielelkin** [comment]
transferred to https://github.com/tsquillario/Jamstash/issues/237
