### ISSUE TITLE
Feature Request: Save queue (and position in queue) across sessions

### ISSUE THREAD

**Issue by btouellette** [tsquillario/Jamstash#236]
If the queue and currently playing song could be stored in local storage or a cookie and reloaded at the start of a new session then I wouldn't lose the queue when Chrome crashes or I have to restart my computer.

**Comment by Hyzual** [comment]
There is already a feature that should help you: in settings > HTML5 > Local storage, there is a checkbox named "Save Progress". It lets you save the queue and current song in local storage. It should be saved again every 30 seconds.

**Comment by btouellette** [comment]
You're right :) Must have forgotten to check that guy when I swapped over to the beta site. Thanks!
