### ISSUE TITLE
Next Button

### ISSUE THREAD

**Issue by thetre97** [tsquillario/Jamstash#239]
I have tried this a couple of times, but the next ( >> ) button doesn't seem to be working?

**Comment by tsquillario** [comment]
You have to have songs in your queue. Try playing or adding a whole album then use next.

**Comment by thetre97** [comment]
yes okay, that works - thanks.
is it not possible to make it go to the next track in an album if I had just clicked play on one track out of an album (w/o adding it all to queue ) for instance?

**Comment by thetre97** [comment]
I see that it does if i select autoplay, but it jumps to a random track rather than the next song in the album...
