### ISSUE TITLE
Please use https

### ISSUE THREAD

**Issue by gerroon** [tsquillario/Jamstash#240]
The dev claims that 

"I NEVER access, read, modify, store, or transmit your personal data." Sure that sounds so awesome, so convincing. He is not saying he is not able to access personal data but he prefers not to.

Lets say he does not access people's stuff by virtue of his ethics but his website exposes people's private files and passwords etc by default because the server is running on http.

**Comment by tsquillario** [comment]
Technically it's up to YOU to use HTTPS to your server. I'm just hosting up static html files from jamstash.com. Any request made with credentials is to your server directly from your browser. It's all done in javascript, I run no server-side code here. If you don't choose to use HTTPS that's on you.
