### ISSUE TITLE
Playlist Actions buttons improperly formatted

### ISSUE THREAD

**Issue by evilmanimani** [tsquillario/Jamstash#241]
![capture](https://cloud.githubusercontent.com/assets/24360832/23818627/cadedf86-05b1-11e7-9802-659db1d068c7.PNG)

As shown in the image the Playlist Actions buttons are mostly hidden when viewing playlists regardless of browser window width, The buttons for select all/none, and +queue/+playlist otherwise look normal when viewing artists or auto albums.

As an aside, is there an option, or is it possible to implement an option for selecting a range of tracks in the queue and browser? Cheers!

**Comment by Hyzual** [comment]
Yes indeed the last button is hidden most of the time.
I don't know when I'll have time to work on this, but I think the Playlist UX in particular should be improved.

Just to be sure, do you mean "Is it possible to select from song A to D without clicking on each song A, B, C, D ?"
If this is what you mean, I'm afraid it isn't possible. This should probably be improved as well

**Comment by evilmanimani** [comment]
I was able to make a couple edits using the Stylish extension to narrow the buttons and change the margins a bit, probably not ideal but it works for now, here's the edits that you can paste into a new style:

`.subactions {
    width: 600px;
    float: left;
    margin: 6px 0 0 0;
}
a.button {
	padding: 6px 5px;
}`

Which will give you this:

![capture](https://cloud.githubusercontent.com/assets/24360832/24157322/4df79806-0e16-11e7-8e78-3d33ab5cfc7f.PNG)

As far as item selection; yes, that was what I was referring to, being able to select just a chunk of a list, rather than selecting them individually or all/none. Thanks for taking a look, cheers.

**Comment by Hyzual** [comment]
Hey, sorry for the late reply :/. Thanks for posting the CSS.
I'm setting up again a working dev environment to commit your code and push a new version. Couldn't finish today, but I'll get to it soon :).

**Comment by Hyzual** [comment]
I've pushed a commit with your changes included. Thanks !
@tsquillario it doesn't look like beta.jamstash.com has been updated, could you please take a look ? I thought that just pushing to `develop` would trigger the update. Let me know if I can help

**Comment by tsquillario** [comment]
Not sure why it isn't working. I'm pointing the domain to different hosting now. Then I'll test out the git hook again. I'll keep you posted...

**Comment by Hyzual** [comment]
Hey thanks for taking a look :) beta.jamstash.com is at the latest version. It seems there is a problem with the certificate for https though, maybe following the different hosting. When I visit with https I get this error (in google chrome)
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by tsquillario** [comment]
I did a manual git clone and copy the files over. I have to fix the git hook still. The new shared hosting is being a bit picky with the git command.
