### ISSUE TITLE
Remote jukebox mode ?

### ISSUE THREAD

**Issue by glucenag** [tsquillario/Jamstash#251]
Hey there ! Sorry for posting here. This is a question, not an issue: with Jamstash can one use the app to remotely *control* the subsonic server machine ? I want something like jukebox mode on the official app (which does not work). So I want to go to Jamstash and tell the *machine* to play a music file - don't want to play it on my phone! Is this at all possible ?

Thanks!

Gustavo

**Comment by pR0Ps** [comment]
I haven't tested it, but jukebox support is built into the application so it should work. Enable it on the settings page and click the little cloud icon in the progress bar at the bottom.

**Comment by glucenag** [comment]
Yeah no it doesn't. There's lots of people out there saying the same BTW,
so you might want to fix that.

Gustavo
