### ISSUE TITLE
BUG: Tracks won't play in Subsonic WebGUI after using Minisub

### ISSUE THREAD

**Issue by jsgates** [tsquillario/Jamstash#98]
I have experienced this issue since I started using Minisub with Subsonic 4.7.  I am currently running Subsonic 4.8.  Minisub works great for playing my music.  However, after using Minisub, when I log back into Subsonic via the basic web interface, even from a different machine, I am unable to play tracks.  If I browse to an album in the basic Subsonic web interface and click the "play" button next to the track, instead of playing the track it tries to download a "play1.m3u".  In addition if I try to click on a track title in an existing playlist, the track is simply not clickable.  The only way to restore proper functionality to the Subsonic WebGUI is the restart the Subsonic service.  This happens every time after using Minisub.   

Subsonic 4.8 running on Ubuntu Server
Google Chrome Browser Version 26.0.1410.64 m  on Windows XP

**Comment by laike9m** [comment]
same here.

**Comment by Goundski** [comment]
Same here.

**Comment by tsquillario** [comment]
In Subsonic, look at Settings > Players. Try deleting some of those or changing the options.

**Comment by 1equalmusic** [comment]
I changed the MiniSub player option back to Web player, and all good - in Chrome on a PC, at least.
